version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/examples/basic"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/examples/typescript"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
