version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: cypress
    versions:
    - 6.8.0
    - 7.0.1
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/examples/basic"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/examples/typescript"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
